services:

  mongo:
    build: ./mongo
    container_name: discharge_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  dischargeflow_agent_main:
    build: ./dischargeflow_agent_main
    container_name: dischargeflow_agent_main
    ports:
      - "9000:9000"
    depends_on:
      - mongo
    environment:
      MONGO_URL: "mongodb://mongo:27017"
      DB_NAME: "dischargeflow_db"
    env_file:
      - ./dischargeflow_agent_main/.env
    volumes:
      - ./dischargeflow_agent_main:/app

  backend:
    build: ./backend
    container_name: discharge_backend
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      MONGO_URL: "mongodb://mongo:27017/dischargeflow_db"

  frontend:
    build: ./frontend
    container_name: discharge_frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend
    environment:
      VITE_API_URL: "http://localhost:8000/api/patientcare"
    restart: unless-stopped
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev -- --host

volumes:
  mongo_data:
